server:
  port: 20010

spring:
  application:
    name: user-service
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    time-zone: Asia/Shanghai


