server:
  port: 10010

spring:
  application:
    name: zuul-server
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    time-zone: Asia/Shanghai

# 参考 org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration
# 参考 org.springframework.cloud.netflix.ribbon.okhttp.OkHttpRibbonConfiguration
ribbon:
  okhttp:
    enabled: true
  http:
    client:
      enabled: false
  # 单位毫秒
  ReadTimeout: 20_000
  # Ribbon连接池大小
  MaxTotalConnections: 315
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0


logging:
  level:
    root: info
    com.netflix.discovery: info
    org.apache.http: info


